### ISSUE TITLE
Support Focus/ Defocus

### ISSUE THREAD

**Issue by Stefflan00** [bcbcarl/react-c3js#12]
Since i want to build a custom Legend (http://c3js.org/samples/legend_custom.html) I need to focus and defocus.
Or did i miss s.th. how it is possible to achieve that?

**Comment by bcbcarl** [comment]
I use `onrendered` property to custom my chart after C3 rendered.

Example:
```javascript
const chartConfig = {
  data: {
    json: {
      data1: [100],
      data2: [300],
      data3: [200]
    },
    type: 'pie'
  },
  legend: {
    show: false
  },
  onrendered: () => {
    // d3.select here
  }
};
<C3Chart {...chartConfig} />
```

You can also reference the chart object. See also: https://github.com/bcbcarl/react-c3js/issues/2.
