### ISSUE TITLE
Completely re-loading data

### ISSUE THREAD

**Issue by patrickdevivo** [bcbcarl/react-c3js#15]
I seem to be having some trouble rendering a chart when the data I pass in periodically updates while the chart component remains mounted.

Basically I believe the issue has to do with how C3 loads new data. For my case, and I would imagine generally, if the `data` prop changes, the old data should be `unloaded` before the new is `loaded` so that odd conflicts don't occur. When `.load` alone is called, C3 tries to append or merge that data on to the existing chart.

Am I completely off-base here? Please let me know

**Comment by patrickdevivo** [comment]
I ended up building a custom solution into my React project using the `c3` package directly.

What I found was that re-generating the chart when new data arrived (via `props`) ended up being an easier way to update the chart (rather than `unload`/`load`). I'm not sure about the performance concerns of this, but I will keep experimenting....

**Comment by maZahaca** [comment]
@patrickdevivo Could you provide an example, I have to do similar behavior.

**Comment by patrickdevivo** [comment]
```javascript
    componentDidMount() {
        this.initChart();
    }

    componentWillUnmount() {
        this.destroyChart();
    }

    componentDidUpdate() {
        this.destroyChart();
        this.initChart();
    }

    @autobind
    initChart() {
        const {data, id} = this.props;
        if (this.chartNode) {
            this.chart = c3.generate({
                bindto: this.chartNode,
                data
                }
            });
        }

    }


    @autobind
    destroyChart() {
        this.chart.destroy()
    }

```

@maZahaca

**Comment by bcbcarl** [comment]
@patrickdevivo: C3 leaks a lot of memory if you regenerate a chart repeatly.

**Comment by patrickdevivo** [comment]
@bcbcarl hmm thanks for the heads up. I'm having quite a bit of trouble getting `chart.unload` and `chart.load` to work properly though. Have you seen any resources for completely re-loading a dataset around?

My issues seem to be around resetting axis I believe

**Comment by maZahaca** [comment]
Have you seen that solution https://www.pubnub.com/developers/eon/chart/spline/ ?
It's based on c3. But it's not free.

If you find a way to do appropriate re-loading, please let me know. I will be fighting for this soon :)
Thanks

**Comment by pencilcheck** [comment]
I found out for donut chart, a lot of times I update the props and expect a rerender to happen and refresh the chart correctly, but everytime it does that it partially works, the labels, percentage text shows up the right amount but for some reason the actual pie segment is still showing the old data. Is this a bug in react-c3js or is it a bug in c3js?

**Comment by dqunbp** [comment]
@patrickdevivo 
I have the same behaviour

**Comment by becgabri** [comment]
Use the unload property in data instead and set it to true. https://github.com/bcbcarl/react-c3js/pull/16

**Comment by MLEKMAD** [comment]
I had the same problem,
set **unload** property in data to true.
