### ISSUE TITLE
question

### ISSUE THREAD

**Issue by joeshub** [bcbcarl/react-c3js#2]
Question: how would I get a reference to the chart object in the component to do things like this with it? http://c3js.org/samples/legend_custom.html

Thank you!

**Comment by davellx** [comment]
Have you tried <C3Chart ref="MyChart" data={this.state.data} /> and then in your component : 
```javascript
componentDidUpdate(){
      var myChart = this.refs.myChart.chart;
      // do what you want with myChart
  }
```
?

**Comment by joeshub** [comment]
Oh I see, thank u @davellx
