### ISSUE TITLE
Missing object assign polyfill in IE

### ISSUE THREAD

**Issue by forum-is** [bcbcarl/react-c3js#20]
Hello and thank you for creating react-c3js! It performs great in Chrome and Firefox.

However it won't work in IE, which we are sadly forced to support. :-(
The reason is missing support of Object.assign, causing a breaking error in generateChart. 

The issue can easily be solved by adding:
`"babel": {
  "plugins": [
    "transform-object-assign"
  ]
}`
to the package.json to provide a polyfill.

Please consider!

**Comment by bcbcarl** [comment]
Landed patch:
https://github.com/bcbcarl/react-c3js/commit/e0262cd7ebb293dda5a5fc0d086d22f1ba142fa3

**Comment by forum-is** [comment]
Thanks, that was quick! :1st_place_medal:
