### ISSUE TITLE
x axis categories are not showing instead it shows 0 1 2

### ISSUE THREAD

**Issue by dineshu07** [bcbcarl/react-c3js#26]
Hello 

I'm tried small example from c3js example. graph is showing but x axis categories are not showing 

my code 

```
import React, { Component } from 'react';
import C3Chart from 'react-c3js';
import '../css/c3.css';

let chartData = {
    "axis": {
      "x": {
        "categories": [
          "india","uk","usa","brazil","france","germany","italy","nepal","malaysia"],
        "type": "category"
      }
    },
      "columns": [
        [
          "sales",30,200,100,400,150,250,50,100,250
        ],
        [
          "margin",10,100,30,300,50,50,10,0,50
          ]
      ],
      "type": "bar"
    
  }
```

```

export default class BarChartComp extends Component {


  render() {

    return (
      <C3Chart data={chartData} />
    );
  }
}

```
Result : 
![screenshot from 2017-06-15 12 26 08](https://user-images.githubusercontent.com/13025236/27169072-ed176e8c-51c5-11e7-9a10-bba92e0eaf3d.png)

expected results

![screenshot from 2017-06-15 12 29 50](https://user-images.githubusercontent.com/13025236/27169167-5a5e8fc0-51c6-11e7-923d-640ae8e68f8c.png)

What I'm missing? the same example shows categories in c3. but not in react.It would be great help.

Thanks in advance
Dinesh

**Comment by CASandmann** [comment]
`axis` is supposed to be supplied as its own prop to the component.  Like:

```
let chartData = {
  "columns": [
    [
      "sales",30,200,100,400,150,250,50,100,250
    ],
    [
      "margin",10,100,30,300,50,50,10,0,50
    ]
  ],
  "type": "bar"
};
let axis = {
  "x": {
    "categories": [
      "india","uk","usa","brazil","france","germany","italy","nepal","malaysia"],
    "type": "category"
  }
};
...
<C3Chart data={chartData} axis={axis} />
```

This concept applies to other things that used to be part of chartData as well, such as `legend` and `padding`.

**Comment by dineshu07** [comment]
Thank you so much @CASandmann .
