### ISSUE TITLE
Chart not being re-loaded when a column is removed from data

### ISSUE THREAD

**Issue by marcioaffonso** [bcbcarl/react-c3js#32]
If I remove a column from the `data` property, the line is not removed from the chart (chart is not being reloaded).

**Comment by micheledisalvatore** [comment]
@marcioaffonso how did you fix it?

I have the same problem with `type: 'timeseries'` when I remove a column.

I'm using the prop `unloadBeforeLoad`, when I add a column, the chart is reloaded, when I remove a column, the chart is not reloaded and everything stays in the same status. 

Anything that I've missed?
