### ISSUE TITLE
Strange black fill in the chart lines

### ISSUE THREAD

**Issue by micahblu** [bcbcarl/react-c3js#35]
With no custom styling and the sample code I get strange black fills in the chart lines.
```js
import C3Chart from 'react-c3js'

const data = {
	columns: [
		['data1', 30, 200, 100, 400, 150, 250],
		['data2', 50, 20, 10, 40, 15, 25]
	]
}

const ServiceSettings = ({ settings, updateSetting }) => {

	return (
		<div className="service-settings"> 
			<C3Chart data={data} />

```

<img width="747" alt="screen shot 2018-01-18 at 3 49 20 pm" src="https://user-images.githubusercontent.com/441559/35127561-866597e8-fc67-11e7-956d-18d02b3be871.png">

**Comment by theonlyfox** [comment]
You need to add c3.css to your file or fix its link.  Had the same issue with my charts and had to stumble on the solution.

**Comment by micahblu** [comment]
Thank you, that was the issue!
