### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getItem' of undefined in Chrome: 54.0.2840.87

### ISSUE THREAD

**Issue by gunjaagrawal** [bcbcarl/react-c3js#7]
Gettting this error on bar charts when hovered over bars. Works perfectly fine on mozilla.
I found a similar issue for c3js - https://github.com/c3js/c3/issues/1566 and looks like the fix is available.
Are you planning to merge this fix in react-c3js as well?

**Comment by bcbcarl** [comment]
Thanks a lot. I just upgraded c3js to `0.4.11`.
See: https://github.com/bcbcarl/react-c3js/commit/cd18f711707332ee6850de17024cf39ad9fbdf42
